import csv
from itertools import product

# Lists of coding projects and programming languages/frameworks
projects = [
    "personal blog",
    "weather app",
    "e-commerce website",
    "chat application",
    "portfolio website",
    "task manager",
    "fitness tracker",
    "social media platform",
    "budget tracker",
    "recipe app",
    "game (e.g., Tic-Tac-Toe)",
    "portfolio website",
    "inventory management system",
    "online forum",
    "blog platform",
    "movie recommendation system",
    "travel booking site",
    "music streaming service",
    "online education platform",
    "real-time collaboration tool",
    "news aggregator",
    "image gallery",
    "event scheduling app",
    "quiz application",
    "virtual reality experience",
    "IoT dashboard",
    "machine learning model deployment",
    "mobile banking app",
    "cryptocurrency tracker",
    "AI chatbot",
    "content management system",
    "survey tool",
    "file sharing service",
    "appointment booking system",
    "language learning app",
    "stock market analyzer",
    "email marketing tool",
    "customer relationship management (CRM) system",
    "HR management tool",
    "expense reporting system",
    "time tracking app",
    "virtual assistant",
    "healthcare management system",
    "project management tool",
    "e-learning course platform",
    "dating app",
    "food delivery service",
    "ride-sharing app",
    "property listing website",
    "online ticketing system",
    "fitness class booking app",
    "news publication website",
    "subscription box service",
    "digital wallet",
    "gift registry app",
    "pet adoption platform",
    "virtual event platform",
    "crowdfunding website",
    "document editing tool",
    "resume builder",
    "video conferencing app",
    "password manager",
    "inventory tracking app",
    "content aggregator",
    "language translation tool",
    "weather forecasting system",
    "financial planning app",
    "remote desktop application",
    "online survey platform",
    "task automation tool",
    "image editing software",
    "digital art gallery",
    "online marketplace",
    "booking management system",
    "travel itinerary planner",
    "fleet management system",
    "resource scheduling app",
    "user authentication system",
    "data visualization dashboard",
    "API development platform",
    "server monitoring tool",
    "log management system",
    "code collaboration platform",
    "bug tracking tool",
    "feature flagging system"
]

languages_frameworks = [
    "Python",
    "JavaScript",
    "Java",
    "C#",
    "Ruby",
    "Go",
    "Swift",
    "Kotlin",
    "PHP",
    "TypeScript",
    "React",
    "Angular",
    "Vue.js",
    "Django",
    "Flask",
    "Ruby on Rails",
    "Laravel",
    "Spring Boot",
    "Express.js",
    "ASP.NET",
    "Node.js",
    "TensorFlow",
    "Flutter",
    "SwiftUI",
    "React Native",
    "Svelte",
    "Ember.js",
    "Meteor",
    "Bootstrap",
    "Tailwind CSS",
    "Next.js",
    "Nuxt.js",
    "GraphQL",
    "Redux",
    "Docker",
    "Kubernetes",
    "Unity",
    "Unreal Engine",
    "Electron",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "Pytorch",
    "C++",
    "Rust",
    "Scala",
    "Perl",
    "Clojure",
    "Elixir",
    "Haskell",
    "MATLAB",
    "R",
    "ASP.NET Core",
    "SvelteKit",
    "Gatsby",
    "Jekyll",
    "Hugo",
    "WordPress",
    "Drupal",
    "Magento",
    "Shopify",
    "Symfony",
    "CodeIgniter",
    "CakePHP",
    "Zend Framework",
    "ASP.NET MVC",
    "Backbone.js",
    "Ionic",
    "Cordova",
    "Capacitor",
    "NativeScript",
    "Dart",
    "Cypress",
    "Jasmine",
    "Mocha",
    "Jest",
    "Selenium",
    "Protractor",
    "TestCafe",
    "Cucumber",
    "Grails",
    "Play Framework",
    "Phoenix",
    "Sinatra",
    "Bottle",
    "CherryPy",
    "Slim",
    "CodeIgniter",
    "Zend",
    "FuelPHP",
    "Yii",
    "Phalcon",
    "Zend Expressive",
    "Slim Framework"
]

# Generate all possible combinations
query_template = "How do I make a {project} with {language_framework}?"
queries = [query_template.format(project=proj, language_framework=lang_fw) 
           for proj, lang_fw in product(projects, languages_frameworks)]

# Optionally, limit the number of queries to prevent extremely large CSVs
# For example, take first 1000 combinations
# queries = queries[:1000]

# Save to CSV
csv_filename = "search_queries.csv"
with open(csv_filename, mode='w', newline='', encoding='utf-8') as csv_file:
    writer = csv.writer(csv_file)
    writer.writerow(["Search Query"])  # Header
    for query in queries:
        writer.writerow([query])

print(f"Generated {len(queries)} search queries and saved to '{csv_filename}'.")
